### ISSUE TITLE
Why so awesome

### ISSUE THREAD

**Issue by sojohnnysaid** [AbdulHamidDabboussi/DesktopCleaner#1]
It is unfair to make such awesome software, please make less awesome. I have a hard time coding my hello world python project with tears in my eyes.

![image](https://user-images.githubusercontent.com/16521766/41738531-48d00e96-7560-11e8-907f-a8fe12a9d908.png)

**Comment by msafadieh** [comment]
@sojohnnysaid I see you've stumbled on my friend's GitHub project, John! :-)

**Comment by AbdulHamidDabboussi** [comment]
Thank you!! @sojohnnysaid
